variable "environment" {
  description = "Name of the environment; will be prefixed to all resources"
  type        = string
}

variable "name" {
  description = "Name of the resource."
  type        = string
}

variable "vpc_id" {
  description = "EFS is created in this VPC"
  type        = string
}

variable "subnet_ids" {
  description = "The created EFS will be available in these subnet ids"
  type        = list(string)
}

variable "encrypted" {
  description = "Encrypt file system."
  type        = bool
  default     = true
}

variable "performance_mode" {
  description = "maxIO"
  type        = string
  default     = "generalPurpose"
}

variable "creation_token" {
  description = "A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. "
  type        = string
  default     = ""
}

variable "mount_location" {
  description = "Mount location if you want to get cloud-init command part"
  type        = string
  default     = ""
}

variable "tags" {
  description = "A map of tags to add to the resources"
  type        = map(string)
  default     = {}
}

